/* فهرست آهنگ‌ها برای صفحات سایت (id ها با play.html یکی است) */
window.CATALOG=[
 {id:'gf',        name:'آبشار جاذبه',            info:'Gravity Falls — تم سریال', cat:'کارتون',  dif:'m', ico:'🌲'},
 {id:'elise',     name:'برای الیز',              info:'Für Elise — بتهوون',        cat:'کلاسیک', dif:'h', ico:'🎼'},
 {id:'hp',        name:'هری پاتر',               info:"Hedwig's Theme",            cat:'فیلم',   dif:'h', ico:'⚡'},
 {id:'pirates',   name:'دزدان دریایی کارائیب',   info:"He's a Pirate",             cat:'فیلم',   dif:'h', ico:'🏴‍☠️'},
 {id:'tetris',    name:'تتریس',                  info:'Korobeiniki',               cat:'بازی',   dif:'m', ico:'🧩'},
 {id:'joy',       name:'سرود شادی',              info:'Ode to Joy — بتهوون',       cat:'کلاسیک', dif:'e', ico:'🎉'},
 {id:'twinkle',   name:'ستاره کوچولو',           info:'Twinkle Twinkle',           cat:'کودکانه',dif:'e', ico:'⭐'},
 {id:'birthday',  name:'تولدت مبارک',            info:'Happy Birthday',            cat:'کودکانه',dif:'e', ico:'🎂'},
 {id:'river',     name:'River Flows in You',     info:'یی‌روما',                   cat:'مدرن',   dif:'m', ico:'🌊'},
 {id:'canon',     name:'کانن در ر',              info:'Canon in D — پاخلبل',       cat:'کلاسیک', dif:'m', ico:'💐'},
 {id:'jingle',    name:'جینگل بلز',              info:'Jingle Bells',              cat:'کودکانه',dif:'e', ico:'🔔'},
 {id:'lion',      name:'شیرشاه',                 info:'Circle of Life',            cat:'کارتون', dif:'m', ico:'🦁'},
 {id:'godfather', name:'پدرخوانده',              info:'The Godfather — تم عشق',    cat:'فیلم',   dif:'m', ico:'🎩'},
 {id:'titanic',   name:'تایتانیک',               info:'My Heart Will Go On',       cat:'فیلم',   dif:'m', ico:'🚢'},
 {id:'undertale', name:'Megalovania',            info:'Undertale',                 cat:'بازی',   dif:'h', ico:'💀'},
 {id:'mario',     name:'سوپر ماریو',             info:'Super Mario Bros',          cat:'بازی',   dif:'m', ico:'🍄'},
 {id:'nokia',     name:'زنگ نوکیا',              info:'Nokia Tune',                cat:'مدرن',   dif:'e', ico:'📱'},
 {id:'interstellar',name:'میان‌ستاره‌ای',        info:'Interstellar — هانس زیمر',  cat:'فیلم',   dif:'m', ico:'🚀'},
 {id:'zelda',     name:'لالایی زلدا',            info:"Zelda's Lullaby — نینتندو", cat:'بازی',   dif:'m', ico:'🗡️'},
 {id:'moonlight', name:'سونات مهتاب',            info:'بتهوون — آرپژ',             cat:'کلاسیک', dif:'h', ico:'🌙'},
 {id:'imperial',  name:'مارش امپراتوری',         info:'Star Wars — دارث ویدر',     cat:'فیلم',   dif:'h', ico:'🌑'},
 {id:'aval',      name:'آملی',                   info:"Comptine d'un autre été",   cat:'مدرن',   dif:'h', ico:'☕'},
 {id:'ff7',       name:'Final Fantasy VII',      info:'تم اصلی',                   cat:'بازی',   dif:'m', ico:'⚔️'},
 {id:'sadness',   name:'حس تنهایی',              info:'ناروتو — Sadness & Sorrow', cat:'کارتون', dif:'m', ico:'🍥'},
 {id:'fly',       name:'Fly Me to the Moon',     info:'جاز کلاسیک',                cat:'مدرن',   dif:'m', ico:'🌕'},
 {id:'ode2',      name:'گل یاس (Greensleeves)',  info:'فولک انگلیسی',              cat:'کلاسیک', dif:'m', ico:'🌿'}
];
window.DIFN={e:'آسان',m:'متوسط',h:'سخت'};
